name: "ashlar"
description: Alignment by Simultaneous Harmonization of Layer/Adjacency Registration
keywords:
  - image_processing, alignment, registration
tools:
  #
  - "ashlar":
      description: "Alignment by Simultaneous Harmonization of Layer/Adjacency Registration"
      homepage: "https://labsyspharm.github.io/ashlar/"
      documentation: "https://labsyspharm.github.io/ashlar/"
      doi: "10.1093/bioinformatics/btac544"
      licence: "['MIT']"

input:
  #
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', : args: '--flip-x' ]
  - file_in:
      type: path
      description: multidimentional image data in formats from most commercial microscopes
      pattern: "*.ome.tiff"

output:
  #
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', : args: '--flip-x' ]
  - file_out:
      type: file
      description: pyramidal OME-TIFF
      pattern: "*.tif"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@RobJY"
  - "@jmuhlich"
