name: "ashlar"
description: Alignment by Simultaneous Harmonization of Layer/Adjacency Registration
keywords:
  - image_processing, alignment, registration
tools:
  #
  - "ashlar":
      description: "Alignment by Simultaneous Harmonization of Layer/Adjacency Registration"
      homepage: "https://labsyspharm.github.io/ashlar/"
      documentation: "https://labsyspharm.github.io/ashlar/"
      tool_dev_url: "None"
      doi: "10.1101/2021.04.20.440625"
      licence: "['MIT']"

input:
  #
  ## TODO nf-core: need to add optional and default parameters
  - file_in:
      type: file
      description: multidimentional image data in formats from most commercial microscopes
      pattern: "*.ome.tiff"
  - align_channel:
      type: integer
      description: Reference channel number for image alignment. Numbering starts at 0. (default: 0)
      ## TODO nf-core: how do we set a default
  - maximum-shift:
      type: integer
      description: Maximum allowed per-tile corrective shift in microns (default: 15)
      ## TODO nf-core: need to set default
  - tile_size:
      type: integer
      description: Pyramid tile size for OME-TIFF output (default: 1024)
      ## TODO nf-core: need to set default

output:
  #
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  ## TODO nf-core: This just handles one output option.  We also have to handle the case
  ##               where the user requests a series of single-channel plain TIFF files
  ##               by setting the output filename to *.tif
  - file_out:
      type: file
      description: pyramidal OME-TIFF
      pattern: "*.ome.tif"

authors:
  - "@RobJY"
